//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbrall.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbrall.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap factory {
            get {
                object obj = ResourceManager.GetObject("factory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap factory1 {
            get {
                object obj = ResourceManager.GetObject("factory1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap factory11 {
            get {
                object obj = ResourceManager.GetObject("factory11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap factory2 {
            get {
                object obj = ResourceManager.GetObject("factory2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap factory21 {
            get {
                object obj = ResourceManager.GetObject("factory21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home1 {
            get {
                object obj = ResourceManager.GetObject("home1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_pime {
            get {
                object obj = ResourceManager.GetObject("logo_pime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pimelogosize {
            get {
                object obj = ResourceManager.GetObject("pimelogosize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Web Page Design&lt;/title&gt;
        ///	&lt;style&gt;
        ///		table.border {
        ///			border-collapse: collapse;
        ///		}
        ///
        ///		table.border th {
        ///			padding: 5px;
        ///			border: 1px solid black;
        ///		}
        ///
        ///		table.border td {
        ///			padding: 5px;
        ///			border: 1px solid black;
        ///		}
        ///
        ///		html {
        ///			border: 4px solid black;
        ///			!important min-height: 100%;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table style=&quot;width:100%&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;/td&gt;
        ///			&lt;td style=&quot;width:60%&quot; align=&quot;center&quot;&gt;
        ///				&lt;table&gt;
        ///					&lt;tr&gt;&lt;td align= [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantilla {
            get {
                return ResourceManager.GetString("plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Web Page Design&lt;/title&gt;
        ///	&lt;style&gt;
        ///		table.border {
        ///			border-collapse: collapse;
        ///		}
        ///
        ///		table.border th {
        ///			padding: 5px;
        ///			border: 1px solid black;
        ///		}
        ///
        ///		table.border td {
        ///			padding: 5px;
        ///			border: 1px solid black;
        ///		}
        ///		
        ///		
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table style=&quot;width:100%&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;/td&gt;
        ///			&lt;td style=&quot;width:60%&quot; align=&quot;center&quot;&gt;
        ///				&lt;table&gt;
        ///					&lt;tr&gt;&lt;td align=&quot;center&quot;&gt;SISTEMA DE FACTURACIÓN UMBRALL&lt;/td&gt;&lt;/tr&gt;
        ///					&lt;tr&gt;&lt;td align=&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantillaHoraria {
            get {
                return ResourceManager.GetString("plantillaHoraria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Web Page Design&lt;/title&gt;
        ///	&lt;style&gt;
        ///		table.border {
        ///			border-collapse: collapse;
        ///		}
        ///
        ///		table.border th {
        ///			padding: 5px;
        ///			border: 1px solid black;
        ///		}
        ///
        ///		table.border td {
        ///			padding: 5px;
        ///			border: 1px solid black;
        ///		}
        ///
        ///
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table style=&quot;width:100%&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;/td&gt;
        ///			&lt;td style=&quot;width:60%&quot; align=&quot;center&quot;&gt;
        ///				&lt;table&gt;
        ///					&lt;tr&gt;&lt;td align=&quot;center&quot;&gt;SISTEMA DE FACTURACIÓN UMBRALL&lt;/td&gt;&lt;/tr&gt;
        ///					&lt;tr&gt;&lt;td align=&quot;cent [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string plantillaOrdinaria {
            get {
                return ResourceManager.GetString("plantillaOrdinaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
